=== Andrespolijic65/Ejercicio2/ejercicio2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT listapedidos (pedidos*)>
<!ELEMENT pedidos (numeroserie,cantidad,peso?)>
<!ELEMENT numeroserie (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT peso (#PCDATA)>

=== Andrespolijic65/Ejercicio2/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listapedidos SYSTEM "ejercicio2.dtd">
<listapedidos>
    <pedidos>
        <numeroserie>1234</numeroserie>
        <cantidad>5</cantidad>
        <peso>50</peso>
    </pedidos>
    <pedidos>
        <numeroserie>5678</numeroserie>
        <cantidad>2</cantidad>
    </pedidos>

</listapedidos>
